name: ci

on:
  push:

env:
  REGISTRY_IMAGE: ghcr.io/ether/etherpad-go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: Install dependencies
        run: npm install
        working-directory: ./ui
      - name: Install pnpm
        run: npm install -g pnpm@latest
      - name: Install pnpm dependencies
        run: pnpm install
        working-directory: ./ui
      - name: Install admin frontend dependencies
        run: pnpm install
        working-directory: ./admin
      - name: Build
        run:  node build.js
        working-directory: ./ui
      - name: Install dependencies
        run: go mod download
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Generate templ
        run: templ generate
      - name: Build app
        run: go build -o etherpad-go
      - name: Build admin
        run: pnpm run build
        working-directory: ./admin
      - name: Upload assets
        uses: actions/upload-artifact@v6
        with:
          name: built-assets
          path: |
            assets/js/admin/
            assets/js/timeslider/assets/timeslider.js
            assets/js/pad/assets/pad.js
            assets/js/welcome/assets/welcome.js
            assets/css/build/
          retention-days: 1
      - name: Run tests with coverage
        run: |
          go test -v -coverpkg=./... -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html
      - name: Setup SonarQube
        if: github.actor == 'samtv12345' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: warchant/setup-sonar-scanner@v9
      - name: Run SonarQube Scanner
        if: github.actor == 'samtv12345' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          PROJECT_KEY: etherpad-go

      - name: SonarQube Quality Gate Check
        if: github.actor == 'samtv12345' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        timeout-minutes: 5

  build:
    needs:
      - test
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
          - platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - platform: linux/arm/v7
            runs-on: ubuntu-24.04-arm
          - platform: linux/386
            runs-on: ubuntu-latest
          - platform: linux/ppc64le
            runs-on: ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: 'true'
          fetch-depth: '0'
      - name: Download assets
        uses: actions/download-artifact@v7
        with:
          name: built-assets
          path: .
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Login to Github Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.build
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'type=image,push-by-digest=true,name-canonical=true,push=true' || 'type=image,push=false' }}

      - name: Export digest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: 'true'
          fetch-depth: '0'
      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Get last tag and commit hash
        id: vars
        run: |
          TAG=$(git describe --tags --abbrev=0)
          HASH=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=${TAG}-${HASH}" >> $GITHUB_ENV
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          DIGEST_FLAGS=$(for f in *; do printf '%s@sha256:%s ' "$REGISTRY_IMAGE" "$f"; done)
          docker buildx imagetools create -t $REGISTRY_IMAGE:$IMAGE_TAG $DIGEST_FLAGS
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: ether-charts
          repository: ether/ether-charts
          token: ${{ secrets.ETHER_CHART_TOKEN }}
      - name: Change argocd tag
        run: |
          cd ether-charts
          sed -i "s|tag: .*|tag: \"${{ env.IMAGE_TAG }}\"|g" ./values-go.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "chore: bump etherpad-go image to ${{ env.IMAGE_TAG }}"
          git push origin main
